Feature/rss
HackSoc/hacksoc.org pull request #188
Opened 2021-11-02 22:14 UTC by JMAlego

Implementation for RSS/Atom feeds for the website.

- [ ] RSS feed
- [ ] Atom feed
- [ ] Work out correct way to get absolute URL from flask, context.yaml possible?
- [ ] Get feedback about locations
- [ ] Get feedback on information
- [ ] Validate generated XML as RSS/Atom

Fixes #159

2021-11-02 22:16 UTC, JMAlego commented
@LukeMoll do you know the correct way to generate an absolute URL from flask? During development or when running dynamically you can use `url_for` with the `_external=True` parameter (which feels wrong as it is). When freezing we probably need to store the absolute URL in somewhere like `context.yaml` right?

2021-11-02 22:51 UTC, LukeMoll commented
What feels wrong about `_external`? This seems like the most useful way to do it in Flask.

Given the GitHub repository is hard-coded in filters.py, I'd be comfortable hard-coding the website URL.

As per [https://flask.palletsprojects.com/en/2.0.x/api/#flask.url_for](https://flask.palletsprojects.com/en/2.0.x/api/#flask.url_for), we can set the URL root with `SERVER_NAME`. The tricky bit would be handling the difference between development and production environments; the former probably wants it set to `localhost:8000` (icr the port number), but the latter would use the actual webroot. We could set it to always use the actual webroot, but this could hinder development with absolute URLs.

The note in the docs that 
> Configuration values APPLICATION_ROOT and SERVER_NAME are only used when generating URLs outside of a request context.

is concerning, as AIUI we'd always be generating in a request context.

2021-11-12 23:29 UTC, LukeMoll commented
Thanks for working on this, I'll try to give it a good look over on Monday. One quick comment based on the discussion here is that the cannonical URL for the website is *www.* HackSoc.org, so the base URL should probably reflect that. nginx is configured to redirect anyway so it shouldn't matter too much.

2021-11-15 13:06 UTC, LukeMoll requested changes
Other than the minor documentation suggestion, looks good to me, thank you! Have tested RSS and Atom in Akregator and behave as expected.

2021-11-19 17:51 UTC, JMAlego commented on hacksoc_org/routes.py
> +        str: Full HTML page
Ah good spot

2021-11-19 17:57 UTC, LukeMoll approved these changes

2021-11-19 17:58 UTC, merged